name: ai_ci
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.6.5
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - ipython
  - SQLAlchemy
  - requests==2.22.0
  - psycopg2
  - boto3
  - networkx
  - seaborn
  - gensim
  - spacy
  - scikit-learn
  # Put any conda dependencies here

  - pip:
    - python-louvain
    - pyLDAvis
    # Put any pip dependencies here (and no conda ones anywhere below)

  # Tooling requirements (don't edit)
    - tqdm
    - pyyaml
    - tables
    - black
    - blackcellmagic
    - pymysql
    - sqlalchemy
    - click
    - Sphinx
    - sphinxcontrib.napoleon
    - coverage
    - awscli
    - flake8
  - python-dotenv>=0.5.1
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - jq
  - pytest
